# for new versions buy at discord.gg/vast || shop.vast.sh


[ profile ]
enableDev = true
addHype   = true
addPFP    = true
addBio    = true


[ data ]
username  = "" # blank = random
joinGuild = "vast" # invite code ~ blank = dont join
threads   = 10
debug     = true
showLockd = false


[ captcha ]
service  = "CAPSOLVER"
capKey   = 'CAP-58B6679E200F52DD609D3F4DB26652BD'
